# Generated by Django 5.1.7 on 2025-06-03 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0009_desempenho'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('apadrinhado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_recebidas', to='Aplicativo.apadrinhado')),
                ('padrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
