# Generated by Django 5.1.7 on 2025-06-04 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0011_alter_mensagem_destinatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='Aplicativo.apadrinhado'),
        ),
    ]
