# Generated by Django 5.1.7 on 2025-06-04 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0012_alter_mensagem_destinatario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doacao',
            old_name='usuario',
            new_name='colaborador',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='comprovante',
        ),
        migrations.AddField(
            model_name='doacao',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.aluno'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='mensagem_erro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doacao',
            name='sucesso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='tipo',
            field=models.CharField(choices=[('financeira', 'Financeira'), ('material', 'Material')], max_length=20),
        ),
    ]
