# Generated by Django 5.1.7 on 2025-06-04 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0013_rename_usuario_doacao_colaborador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='aluno',
        ),
        migrations.AddField(
            model_name='doacao',
            name='apadrinhado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='Aplicativo.apadrinhado'),
        ),
    ]
