name: CI/CD to Azure Web App

# Dispara este workflow sempre que alguém der push na branch prod (ou manualmente via UI)
on:
  push:
    branches: [ prod ]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1) Pega o código
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Instala Node.js (necessário para Cypress e wait-on)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # 3) Instala dependências Node (Cypress, wait-on, etc)
      - name: Install npm dependencies
        run: npm ci
        working-directory: ./   # assume que o package.json está na raiz

      # 4) Instala Python (para rodar Django)
      - name: Setup Python
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm ci


      - name: Run local server and tests
        run: |
          python manage.py migrate
          python manage.py runserver &
          sleep 5
          npx cypress run

      
      - name: Cleaning testing files
        run: |
          rm .env
          rm cypress.config.js
          rm package-lock.json
          rm package.json
          rm -rf cypress  
        
      # 6) Inicia o servidor Django em background
      - name: Start Django server in background
        run: |
          source venv/bin/activate
          nohup python manage.py runserver 0.0.0.0:8000 &

      # ---------------------------------------------------------
      # 9) Gera o ZIP de deploy (apenas o código relevante)
      # ---------------------------------------------------------
      - name: 📦 Prepare ZIP for deploy
        run: |
          # Gerar ZIP excluindo pastas que não devem ir ao App Service
          zip -r deploy.zip . \
            -x "venv/*" \
            -x ".git/*" \
            -x "cypress/*" \
            -x ".github/*" \
            -x "*.env" \
            -x "media/fotos_perfil/*" \
            -x "__pycache__/*"
          ls -lh deploy.zip

      # ---------------------------------------------------------
      # 10) Login no Azure (via Service Principal)
      # ---------------------------------------------------------
      - name: 🔐 Azure Login
        if: ${{ success() }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ---------------------------------------------------------
      # 11) Deploy ao App Service (ZIP Deploy com Azure CLI)
      # ---------------------------------------------------------
      - name: 🚢 Deploy to Azure Web App (zip deploy)
        if: ${{ success() }}
        env:
          AZURE_RESOURCE_GROUP: crescer-juntos_group   # ajuste conforme seu Resource Group
          AZURE_APP_NAME: crescer-juntos                # ajuste conforme nome exato do App Service
        run: |
          echo "Deploying deploy.zip to Web App '$AZURE_APP_NAME' in Resource Group '$AZURE_RESOURCE_GROUP'..."
          az webapp deployment source config-zip \
            --resource-group $AZURE_RESOURCE_GROUP \
            --name $AZURE_APP_NAME \
            --src deploy.zip

      # ---------------------------------------------------------
      # 12) Notificar caso algo falhe.
      # ---------------------------------------------------------
      - name: 🚨 Notify on failure
        if: ${{ failure() }}
        run: echo "Algum passo falhou! O deploy NÃO foi executado."

