name: CI/CD to Azure Web App

# Dispara este workflow sempre que alguém der push na branch prod (ou manualmente via UI)
on:
  push:
    branches: [ prod ]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1) Pega o código
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Instala Node.js (necessário para Cypress e wait-on)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # 3) Instala dependências Node (Cypress, wait-on, etc)
      - name: Install npm dependencies
        run: npm ci
        working-directory: ./   # assume que o package.json está na raiz

      # 4) Instala Python (para rodar Django)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # ou a versão que seu projeto usa

      # 5) Instala dependências Python e faz migrate
      - name: Install Python dependencies and Migrate
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py migrate --noinput

      - name: Run local server and tests
        run: |
          python manage.py migrate
          python manage.py runserver &
          sleep 5
          npx cypress run

      
      - name: Cleaning testing files
        run: |
          rm .env
          rm cypress.config.js
          rm package-lock.json
          rm package.json
          rm -rf cypress  

      # 9) Se os testes passarem, faz login no Azure
      - name: Azure Login
        if: ${{ success() }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 10) Faz o deploy para o Web App
      - name: Deploy to Web App
        if: ${{ success() }}
        uses: azure/webapps-deploy@v3
        with:
          app-name: crescer-juntos       # substitua pelo nome do seu Web App
          slot-name: Production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      # 11) (Opcional) Notificar em caso de falha nos testes
      - name: Notify on failure
        if: ${{ failure() }}
        run: echo "🚨 Algum teste falhou! O deploy NÃO será efetuado."
